Feature Onboarding and Survey
Xoka74/FlowerApp pull request #7
Opened 2024-11-04 14:07 UTC by fed1v

2024-11-04 14:09 UTC, fed1v commented on hs_err_pid12944.log
эту фигню случайно закоммитил когда фиксил конфликты после rebase этой ветки на dev :(

2024-11-04 17:14 UTC, Xoka74 commented on domain/src/main/java/com/shurdev/domain/repositories/FlowerRepository.kt
удалить шпиона

2024-11-04 17:14 UTC, Xoka74 commented on features/gallery/src/main/java/com/shurdev/gallery/view_model/GalleryFlowerDetailsUiState.kt
удалить шпиена

2024-11-04 17:14 UTC, Xoka74 commented on features/onboarding/.gitignore
можно не добавлять эту строчку, в глобальном гит игноре она уже имеется

2024-11-04 17:14 UTC, Xoka74 commented on features/survey/.gitignore
тут тоже можно файл удалить даже

2024-11-04 17:14 UTC, Xoka74 commented on features/survey/src/androidTest/java/com/shurdev/survey/ExampleInstrumentedTest.kt
лучше удалить, мы тесты пока не собирались писать

2024-11-04 17:14 UTC, Xoka74 commented on features/onboarding/src/test/java/com/shurdev/onboarding/ExampleUnitTest.kt
лучше удалить, мы тесты пока не собирались писать

2024-11-04 17:14 UTC, Xoka74 commented on features/survey/src/main/AndroidManifest.xml
манифесты из модулей тоже можно поудалять, они не нужны

2024-11-04 17:14 UTC, Xoka74 commented on features/survey/src/test/java/com/shurdev/survey/ExampleUnitTest.kt
лучше удалить, мы тесты пока не собирались писать

2024-11-06 14:05 UTC, Xoka74 commented on app/src/main/java/com/shurdev/flowerapp/presentation/FlowerApp.kt
> +                }
Лучше при прохождении опроса просто убирать surveyNavGraph из стэка, таким образом тебя, например, не будет редиректить на Gallery после прохождения опроса во вкладке Profile

2024-11-06 14:05 UTC, Xoka74 commented on features/gallery/src/main/java/com/shurdev/gallery/navigation/GalleryNavigation.kt
> +    popUpTo(0);
Лишняя точка с запятой

2024-11-10 19:51 UTC, CakeWalker1337 requested changes

2024-11-10 19:51 UTC, CakeWalker1337 commented on features/survey/src/main/java/com/shurdev/survey/SurveyScreen.kt
> +    onBackClick: () -> Unit,
минор, колбэки можно упаковать в один интерфейс

2024-11-10 19:51 UTC, CakeWalker1337 commented on features/survey/src/main/java/com/shurdev/survey/SurveyScreen.kt
> +                    onBackClick = onBackClick,
а сюда через метод-референсы прокидывать, типа clickListener::onBackClick

2024-11-10 19:51 UTC, CakeWalker1337 commented on features/survey/src/main/java/com/shurdev/survey/mocks/Questions.kt
> +val QUESTIONS = listOf(
репозиторий появился, по идее эта штука уже не нужна?)

2024-11-10 19:51 UTC, CakeWalker1337 commented on features/survey/src/main/java/com/shurdev/survey/view_model/SurveyViewModel.kt
> +                    println(it)
дебаг)

2024-11-11 17:23 UTC, fed1v commented on features/survey/src/main/java/com/shurdev/survey/view_model/SurveyViewModel.kt
> +                    println(it)
упс)

2024-11-11 17:31 UTC, fed1v commented on features/survey/src/main/java/com/shurdev/survey/mocks/Questions.kt
> +val QUESTIONS = listOf(
этот QUESTIONS теперь только в превьюхах используется, причем в нескольких, поэтому мне показалось что здесь лучше оставить в отдельной переменной, чтобы можно было переиспользовать, а не хардкодить каждый раз

2024-11-12 07:58 UTC, merged